# Avoid-squashing-assets-by-jekyll
# Test change to force rebuild

# Site Settings
locale           : "en-US"
site_theme       : "default"
title            : "Chongzi Chen"
title_separator  : "-"
name             : &name "Chongzi Chen"
description      : &description "Chongzi Chen's academic website"
url              : "[https://ccz031210.github.io](https://ccz031210.github.io)"
baseurl          : ""
repository       : "ccz031210/ccz031210.github.io"

# Site Author
author:
  avatar         : "profile.png"
  name           : "Chongzi Chen"
  bio            : "PhD student in Mathematics"
  location       : "Rochester, NY"
  employer       : "University of Rochester"
  email          : "cchen151@ur.rochester.edu"

# Academic websites
  googlescholar  : "[https://scholar.google.com/citations?user=PS_CX0AAAAAJ](https://scholar.google.com/citations?user=PS_CX0AAAAAJ)"
  # cv           : "/files/CV.pdf" # 以后你上传了 CV.pdf，把最前面的 # 删掉即可

# External Profiles (无需修改，保持默认)
# Helper config for parsing lists of links
# (Below settings are standard for academicpages theme)
collections:
  publications:
    output: true
    permalink: /publications/:path/
  talks:
    output: true
    permalink: /talks/:path/
  teaching:
    output: true
    permalink: /teaching/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true

# Sass/Jekyll Configuration
sass:
  sass_dir: _sass
  style: compressed

include:
  - _pages

# Keep some build configurations standard
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
